import type {
  RedditPost,
  RedditComment,
  ConversationThread,
  SubredditInsight,
  ActivitySignal,
  TrackedKeyword,
  KeywordMatch,
  FeedPost,
  SubredditEligibility,
} from "@/types/reddit";

const now = Date.now() / 1000;
const hours = (h: number) => now - h * 3600;
const days = (d: number) => now - d * 86400;

export const mockPosts: RedditPost[] = [
  {
    id: "post_1",
    title: "We built an open-source alternative to Notion — here's what we learned",
    selftext:
      "After 6 months of building in public, we finally launched our open-source Notion alternative. Here are the key takeaways from our journey...",
    subreddit: "r/startups",
    author: "threadflow_user",
    score: 847,
    numComments: 134,
    createdUtc: hours(3),
    permalink: "/r/startups/comments/abc123",
    url: "",
    isComment: false,
    status: "active",
    hasNewReplies: true,
    unansweredCount: 5,
  },
  {
    id: "post_2",
    title: "How I grew my SaaS to $10k MRR using only Reddit",
    selftext:
      "A detailed breakdown of my Reddit marketing strategy that took my SaaS from $0 to $10k MRR in 8 months...",
    subreddit: "r/SaaS",
    author: "threadflow_user",
    score: 1203,
    numComments: 89,
    createdUtc: hours(12),
    permalink: "/r/SaaS/comments/def456",
    url: "",
    isComment: false,
    status: "important",
    hasNewReplies: true,
    unansweredCount: 3,
  },
  {
    id: "post_3",
    title: "What's your biggest challenge with user onboarding?",
    selftext:
      "Curious to hear from other founders — what's been the hardest part of getting new users activated?",
    subreddit: "r/Entrepreneur",
    author: "threadflow_user",
    score: 156,
    numComments: 67,
    createdUtc: days(1),
    permalink: "/r/Entrepreneur/comments/ghi789",
    url: "",
    isComment: false,
    status: "reply_later",
    hasNewReplies: false,
    unansweredCount: 8,
  },
  {
    id: "comment_1",
    title: "Re: Best tools for indie hackers in 2026?",
    selftext:
      "I've been using a combination of Vercel for hosting, Stripe for payments, and Resend for emails. Total cost under $50/mo until you scale.",
    subreddit: "r/indiehackers",
    author: "threadflow_user",
    score: 234,
    numComments: 12,
    createdUtc: hours(6),
    permalink: "/r/indiehackers/comments/jkl012/comment/xyz",
    url: "",
    isComment: true,
    parentId: "parent_1",
    status: "active",
    hasNewReplies: true,
    unansweredCount: 2,
  },
  {
    id: "post_4",
    title: "The psychology behind viral Reddit posts — a data analysis",
    selftext:
      "I scraped 10,000 top posts across 50 subreddits and found some interesting patterns about what makes content go viral on Reddit...",
    subreddit: "r/dataisbeautiful",
    author: "threadflow_user",
    score: 2451,
    numComments: 203,
    createdUtc: days(2),
    permalink: "/r/dataisbeautiful/comments/mno345",
    url: "",
    isComment: false,
    status: "done",
    hasNewReplies: false,
    unansweredCount: 0,
  },
  {
    id: "comment_2",
    title: "Re: How do you handle negative feedback on your product?",
    selftext:
      "Honestly, the best approach is to treat every piece of criticism as a free consulting session. Most angry users actually care about your product.",
    subreddit: "r/startups",
    author: "threadflow_user",
    score: 89,
    numComments: 5,
    createdUtc: hours(18),
    permalink: "/r/startups/comments/pqr678/comment/abc",
    url: "",
    isComment: true,
    parentId: "parent_2",
    status: "active",
    hasNewReplies: false,
    unansweredCount: 1,
  },
  {
    id: "post_5",
    title: "Launched our AI writing assistant — feedback welcome!",
    selftext:
      "We just launched and would love honest feedback from the community. It's free during beta.",
    subreddit: "r/SideProject",
    author: "threadflow_user",
    score: 312,
    numComments: 45,
    createdUtc: days(3),
    permalink: "/r/SideProject/comments/stu901",
    url: "",
    isComment: false,
    status: "active",
    hasNewReplies: true,
    unansweredCount: 4,
  },
];

export const mockComments: RedditComment[] = [
  {
    id: "c1",
    body: "This is exactly what I've been looking for. How does it handle real-time collaboration?",
    author: "curious_dev",
    score: 45,
    createdUtc: hours(2),
    permalink: "/r/startups/comments/abc123/comment/c1",
    subreddit: "r/startups",
    parentId: "post_1",
    replies: [
      {
        id: "c1_r1",
        body: "We use CRDTs for conflict resolution. It works surprisingly well even with 10+ concurrent editors.",
        author: "threadflow_user",
        score: 67,
        createdUtc: hours(1.5),
        permalink: "/r/startups/comments/abc123/comment/c1_r1",
        subreddit: "r/startups",
        parentId: "c1",
        replies: [],
        isOwnComment: true,
        depth: 1,
      },
      {
        id: "c1_r2",
        body: "That's impressive. Any plans for an API?",
        author: "api_enthusiast",
        score: 12,
        createdUtc: hours(1),
        permalink: "/r/startups/comments/abc123/comment/c1_r2",
        subreddit: "r/startups",
        parentId: "c1",
        replies: [],
        isOwnComment: false,
        depth: 1,
      },
    ],
    isOwnComment: false,
    depth: 0,
  },
  {
    id: "c2",
    body: "Love the approach! We tried something similar but pivoted to B2B. What's your target market?",
    author: "saas_founder",
    score: 23,
    createdUtc: hours(2.5),
    permalink: "/r/startups/comments/abc123/comment/c2",
    subreddit: "r/startups",
    parentId: "post_1",
    replies: [],
    isOwnComment: false,
    depth: 0,
  },
  {
    id: "c3",
    body: "Open source is the way to go. What license are you using?",
    author: "oss_advocate",
    score: 34,
    createdUtc: hours(3),
    permalink: "/r/startups/comments/abc123/comment/c3",
    subreddit: "r/startups",
    parentId: "post_1",
    replies: [
      {
        id: "c3_r1",
        body: "MIT license. We want to keep it as open as possible.",
        author: "threadflow_user",
        score: 28,
        createdUtc: hours(2.8),
        permalink: "/r/startups/comments/abc123/comment/c3_r1",
        subreddit: "r/startups",
        parentId: "c3",
        replies: [
          {
            id: "c3_r1_r1",
            body: "Great choice! That'll help with adoption. We switched from AGPL to MIT and saw 3x more contributors.",
            author: "oss_advocate",
            score: 15,
            createdUtc: hours(2.5),
            permalink: "/r/startups/comments/abc123/comment/c3_r1_r1",
            subreddit: "r/startups",
            parentId: "c3_r1",
            replies: [],
            isOwnComment: false,
            depth: 2,
          },
        ],
        isOwnComment: true,
        depth: 1,
      },
    ],
    isOwnComment: false,
    depth: 0,
  },
];

export const mockThreads: ConversationThread[] = [
  {
    id: "thread_1",
    post: mockPosts[0],
    comments: mockComments,
    lastActivity: hours(1),
    participantCount: 5,
  },
  {
    id: "thread_2",
    post: mockPosts[1],
    comments: [mockComments[0], mockComments[1]],
    lastActivity: hours(4),
    participantCount: 8,
  },
];

export const mockInsights: SubredditInsight[] = [
  {
    name: "r/startups",
    postCount: 12,
    totalScore: 2340,
    avgScore: 195,
    totalComments: 267,
  },
  {
    name: "r/SaaS",
    postCount: 8,
    totalScore: 3105,
    avgScore: 388,
    totalComments: 189,
  },
  {
    name: "r/Entrepreneur",
    postCount: 6,
    totalScore: 890,
    avgScore: 148,
    totalComments: 134,
  },
  {
    name: "r/indiehackers",
    postCount: 5,
    totalScore: 567,
    avgScore: 113,
    totalComments: 78,
  },
  {
    name: "r/dataisbeautiful",
    postCount: 3,
    totalScore: 4200,
    avgScore: 1400,
    totalComments: 312,
  },
  {
    name: "r/SideProject",
    postCount: 4,
    totalScore: 620,
    avgScore: 155,
    totalComments: 89,
  },
];

export const mockSignals: ActivitySignal[] = [
  {
    id: "sig_1",
    type: "new_reply",
    postId: "post_1",
    title: "We built an open-source alternative to Notion",
    subreddit: "r/startups",
    message: "5 new replies on your post",
    timestamp: hours(0.5),
  },
  {
    id: "sig_2",
    type: "trending",
    postId: "post_2",
    title: "How I grew my SaaS to $10k MRR",
    subreddit: "r/SaaS",
    message: "Your post is trending — 1.2k upvotes",
    timestamp: hours(1),
  },
  {
    id: "sig_3",
    type: "unanswered",
    postId: "post_3",
    title: "What's your biggest challenge with user onboarding?",
    subreddit: "r/Entrepreneur",
    message: "8 comments awaiting your reply",
    timestamp: hours(2),
  },
  {
    id: "sig_4",
    type: "new_reply",
    postId: "comment_1",
    title: "Re: Best tools for indie hackers in 2026?",
    subreddit: "r/indiehackers",
    message: "2 new replies to your comment",
    timestamp: hours(3),
  },
  {
    id: "sig_5",
    type: "unanswered",
    postId: "post_5",
    title: "Launched our AI writing assistant",
    subreddit: "r/SideProject",
    message: "4 comments awaiting your reply",
    timestamp: hours(5),
  },
];

// --- Keyword Monitoring ---

export const mockKeywords: TrackedKeyword[] = [
  {
    id: "kw_1",
    keyword: "project management tool",
    subreddits: ["r/startups", "r/SaaS", "r/Entrepreneur", "r/smallbusiness"],
    createdAt: days(7),
    matchCount: 23,
    isActive: true,
  },
  {
    id: "kw_2",
    keyword: "notion alternative",
    subreddits: ["r/productivity", "r/startups", "r/SelfHosted"],
    createdAt: days(5),
    matchCount: 18,
    isActive: true,
  },
  {
    id: "kw_3",
    keyword: "best CRM for startups",
    subreddits: [],
    createdAt: days(3),
    matchCount: 9,
    isActive: true,
  },
  {
    id: "kw_4",
    keyword: "team collaboration software",
    subreddits: ["r/SaaS", "r/RemoteWork"],
    createdAt: days(10),
    matchCount: 14,
    isActive: false,
  },
];

export const mockKeywordMatches: KeywordMatch[] = [
  {
    id: "km_1",
    keywordId: "kw_1",
    keyword: "project management tool",
    postTitle: "What project management tool do you use for a team of 5?",
    postBody:
      "We're a small startup (5 people) and Jira feels way too heavy. Looking for something lightweight that doesn't require a PhD to set up. Budget is under $20/user/mo. What are you all using?",
    subreddit: "r/startups",
    author: "lean_founder_23",
    score: 67,
    numComments: 43,
    createdUtc: hours(1),
    permalink: "/r/startups/comments/km_1",
    opportunityScore: 92,
    isComment: false,
    replied: false,
  },
  {
    id: "km_2",
    keywordId: "kw_2",
    keyword: "notion alternative",
    postTitle: "Moving away from Notion — need a self-hosted alternative",
    postBody:
      "Notion just increased their pricing again and we have 200+ docs. Looking for something we can self-host. Must have: real-time collab, markdown support, API. Nice to have: kanban boards, databases.",
    subreddit: "r/SelfHosted",
    author: "devops_mike",
    score: 234,
    numComments: 89,
    createdUtc: hours(2),
    permalink: "/r/SelfHosted/comments/km_2",
    opportunityScore: 95,
    isComment: false,
    replied: false,
  },
  {
    id: "km_3",
    keywordId: "kw_3",
    keyword: "best CRM for startups",
    postTitle: "Honest question: what's the best CRM for startups that doesn't cost $$$?",
    postBody:
      "Tried HubSpot (too complex), Pipedrive (missing features), Close (too expensive). I just need contact management + deal tracking + email integration. Under $30/mo for 3 users.",
    subreddit: "r/SaaS",
    author: "bootstrapped_biz",
    score: 156,
    numComments: 78,
    createdUtc: hours(3),
    permalink: "/r/SaaS/comments/km_3",
    opportunityScore: 88,
    isComment: false,
    replied: false,
  },
  {
    id: "km_4",
    keywordId: "kw_1",
    keyword: "project management tool",
    postTitle: "Our team just switched from Monday.com — here's why",
    postBody:
      "Monday.com kept adding bloat and raising prices. We switched to a simpler project management tool and our team is actually using it now. The key was finding something that didn't try to be everything.",
    subreddit: "r/Entrepreneur",
    author: "pm_refugee",
    score: 312,
    numComments: 56,
    createdUtc: hours(5),
    permalink: "/r/Entrepreneur/comments/km_4",
    opportunityScore: 76,
    isComment: false,
    replied: false,
  },
  {
    id: "km_5",
    keywordId: "kw_2",
    keyword: "notion alternative",
    postTitle: "I compared 8 Notion alternatives — here's my honest ranking",
    postBody:
      "Spent the last 2 weeks testing every major Notion alternative. Criteria: speed, offline support, collaboration, API, pricing. Here's my full breakdown...",
    subreddit: "r/productivity",
    author: "tool_reviewer",
    score: 1089,
    numComments: 203,
    createdUtc: hours(8),
    permalink: "/r/productivity/comments/km_5",
    opportunityScore: 84,
    isComment: false,
    replied: true,
  },
  {
    id: "km_6",
    keywordId: "kw_3",
    keyword: "best CRM for startups",
    postBody:
      "I've tried almost every CRM out there and honestly the best CRM for startups is one that your team will actually use. Fancy features don't matter if nobody opens it.",
    postTitle: "Re: What CRM do you recommend for early-stage startups?",
    subreddit: "r/Entrepreneur",
    author: "saas_veteran",
    score: 45,
    numComments: 8,
    createdUtc: hours(4),
    permalink: "/r/Entrepreneur/comments/km_6",
    opportunityScore: 71,
    isComment: true,
    replied: false,
  },
  {
    id: "km_7",
    keywordId: "kw_1",
    keyword: "project management tool",
    postTitle: "Built a project management tool — looking for beta testers",
    postBody:
      "I've been working on a minimalist project management tool focused on developer teams. It integrates with GitHub and has a CLI. Would love some early feedback.",
    subreddit: "r/SideProject",
    author: "indie_builder",
    score: 89,
    numComments: 34,
    createdUtc: hours(10),
    permalink: "/r/SideProject/comments/km_7",
    opportunityScore: 62,
    isComment: false,
    replied: false,
  },
  {
    id: "km_8",
    keywordId: "kw_2",
    keyword: "notion alternative",
    postBody:
      "Has anyone found a good notion alternative that actually works offline? I'm on flights constantly and losing edits is killing me.",
    postTitle: "Need an offline-first Notion alternative",
    subreddit: "r/productivity",
    author: "road_warrior",
    score: 178,
    numComments: 45,
    createdUtc: hours(6),
    permalink: "/r/productivity/comments/km_8",
    opportunityScore: 90,
    isComment: false,
    replied: false,
  },
];

// --- Reddit Feed (browsing experience) ---

export const mockFeedPosts: FeedPost[] = [
  {
    id: "feed_1",
    title: "After 2 years of bootstrapping, we just crossed $1M ARR. Here's every mistake we made.",
    selftext:
      "Two years ago I quit my FAANG job to build a B2B SaaS. Everyone told me I was crazy. Here's the raw, unfiltered story — including the 3 times we almost ran out of money, why our first product completely failed, and the one pivot that changed everything. Happy to answer any questions in the comments.",
    subreddit: "r/startups",
    author: "ex_faang_founder",
    score: 3847,
    numComments: 456,
    createdUtc: hours(2),
    permalink: "/r/startups/comments/feed_1",
    flair: "Milestone",
  },
  {
    id: "feed_2",
    title: "I analyzed 500 landing pages that convert above 10%. Here are the 7 patterns they all share.",
    selftext:
      "Data nerd here. I spent the last month analyzing high-converting landing pages across SaaS, e-commerce, and info products. The results surprised me. Pattern #1: None of them lead with features...",
    subreddit: "r/Entrepreneur",
    author: "conversion_nerd",
    score: 2156,
    numComments: 234,
    createdUtc: hours(4),
    permalink: "/r/Entrepreneur/comments/feed_2",
    flair: "Research",
  },
  {
    id: "feed_3",
    title: "Stop building features nobody asked for. Start doing this instead.",
    selftext:
      "Every week I see founders on here asking for feedback on features they spent months building. The pattern is always the same: they assumed they knew what users wanted instead of asking. Here's the 5-step validation framework that saved us from building 3 unnecessary features last quarter.",
    subreddit: "r/SaaS",
    author: "lean_pm",
    score: 892,
    numComments: 167,
    createdUtc: hours(6),
    permalink: "/r/SaaS/comments/feed_3",
  },
  {
    id: "feed_4",
    title: "The uncomfortable truth about 'building in public'",
    selftext:
      "Hot take: 90% of 'building in public' is just performative content creation disguised as transparency. Real transparency means sharing your churn rate, not just your MRR screenshots. Here's what actual transparency looks like and why most founders avoid it.",
    subreddit: "r/indiehackers",
    author: "honest_builder",
    score: 1534,
    numComments: 312,
    createdUtc: hours(8),
    permalink: "/r/indiehackers/comments/feed_4",
    flair: "Discussion",
  },
  {
    id: "feed_5",
    title: "We replaced our entire marketing team with 2 people + AI. Revenue went UP.",
    selftext:
      "Before you grab pitchforks — we didn't fire anyone, we restructured as people left. Instead of hiring replacements, we gave 2 senior marketers AI tools and full autonomy. 6 months later: 40% less spend, 23% more qualified leads. Here's exactly what tools they use and how the workflow changed.",
    subreddit: "r/marketing",
    author: "ai_marketing_ceo",
    score: 4201,
    numComments: 589,
    createdUtc: hours(3),
    permalink: "/r/marketing/comments/feed_5",
    flair: "Case Study",
  },
  {
    id: "feed_6",
    title: "My cold email got a 34% reply rate. Here's the exact template.",
    selftext:
      "Sent 200 cold emails last month. 68 replies, 23 demos booked, 7 closed deals. The secret? I stopped talking about my product in the first email entirely. Here's the template and the psychology behind each line.",
    subreddit: "r/sales",
    author: "cold_email_king",
    score: 1876,
    numComments: 203,
    createdUtc: hours(5),
    permalink: "/r/sales/comments/feed_6",
  },
  {
    id: "feed_7",
    title: "I spent $50k on Reddit ads in 2025. Here's what worked and what was a complete waste.",
    selftext:
      "Our startup ran Reddit ads across 12 subreddits for 6 months. Total spend: $50k. I'm sharing our full breakdown — CPCs, conversion rates, and the 3 subreddits that drove 80% of our signups. Spoiler: the targeting options are terrible but the intent quality is unmatched.",
    subreddit: "r/GrowthHacking",
    author: "paid_growth_pm",
    score: 967,
    numComments: 145,
    createdUtc: hours(10),
    permalink: "/r/GrowthHacking/comments/feed_7",
    flair: "Data",
  },
  {
    id: "feed_8",
    title: "Why your SaaS pricing page is losing you customers (with real examples)",
    selftext:
      "I've consulted on pricing for 40+ SaaS companies. The same 5 mistakes show up on almost every pricing page. I'm going to roast some real examples (with permission) and show you what the fix looks like. Thread incoming.",
    subreddit: "r/SaaS",
    author: "pricing_consultant",
    score: 2340,
    numComments: 278,
    createdUtc: hours(7),
    permalink: "/r/SaaS/comments/feed_8",
  },
  {
    id: "feed_9",
    title: "We got 10k users in 2 weeks from a single Reddit comment. Here's the thread.",
    selftext:
      "No ads, no influencers, no Product Hunt launch. Just one well-timed, genuinely helpful comment in r/webdev that happened to mention our tool. It hit the top of the thread and the rest is history. Sharing the exact comment and what made it work.",
    subreddit: "r/startups",
    author: "organic_growth_ftw",
    score: 5102,
    numComments: 634,
    createdUtc: hours(1),
    permalink: "/r/startups/comments/feed_9",
    flair: "Growth",
  },
  {
    id: "feed_10",
    title: "I track every hour I work. After 1 year of data, here's what actually moves the needle.",
    selftext:
      "Solopreneur here. I logged every working hour for 365 days and categorized them into: building, marketing, sales, admin, and learning. The results were eye-opening. Building was only 22% of my time but drove 70% of revenue growth. Marketing was 35% of my time but...",
    subreddit: "r/Entrepreneur",
    author: "time_tracker_guy",
    score: 1678,
    numComments: 198,
    createdUtc: hours(9),
    permalink: "/r/Entrepreneur/comments/feed_10",
    flair: "Data",
  },
];

// --- Subreddit Eligibility ---

export const mockEligibility: SubredditEligibility[] = [
  {
    subreddit: "r/startups",
    status: "ready",
    userKarma: 2450,
    userCommentKarma: 1230,
    requirements: [
      { type: "min_karma", label: "Minimum 100 karma", threshold: 100, met: true, current: 2450, progress: 100 },
      { type: "min_account_age", label: "Account at least 30 days old", threshold: 30, met: true, current: 365, progress: 100 },
    ],
    contentRules: [
      { id: "s1", title: "No direct app/product links in posts", description: "Do not post direct links to your product, app, or landing page. Share your story and let people ask for the link.", severity: "remove", category: "links" },
      { id: "s2", title: "Self-promotion ratio: 10%", description: "No more than 10% of your posts/comments should be self-promotional. You must be an active community member first.", severity: "ban", category: "self_promotion" },
      { id: "s3", title: "No launch posts without traction", description: "\"Just launched\" posts must include metrics, learnings, or a specific question. Pure announcements are removed.", severity: "remove", category: "content_type" },
      { id: "s4", title: "Flair your post", description: "All posts must have appropriate flair. Unflaired posts are auto-removed.", severity: "remove", category: "formatting" },
    ],
    restrictions: [],
    canPost: true,
    canComment: true,
  },
  {
    subreddit: "r/Entrepreneur",
    status: "ready",
    userKarma: 2450,
    userCommentKarma: 1230,
    requirements: [
      { type: "min_karma", label: "Minimum 50 karma", threshold: 50, met: true, current: 2450, progress: 100 },
    ],
    contentRules: [
      { id: "e1", title: "No links to your own site/app", description: "External links to your own website, app, or product are not allowed in posts. You may mention them in comments if directly relevant and asked for.", severity: "remove", category: "links" },
      { id: "e2", title: "Self-promotion only on Saturdays", description: "Self-promotional content is only allowed in the weekly Saturday Self-Promotion thread. Posts outside this thread will be removed.", severity: "remove", category: "self_promotion" },
      { id: "e3", title: "No affiliate or referral links", description: "Affiliate links, referral codes, and tracking links are banned. Offenders receive a permanent ban.", severity: "ban", category: "spam" },
      { id: "e4", title: "Provide value first", description: "If sharing your experience, focus on actionable takeaways. \"I made $X\" posts without substance are removed.", severity: "remove", category: "content_type" },
    ],
    restrictions: ["Self-promotion limited to Saturday threads"],
    canPost: true,
    canComment: true,
  },
  {
    subreddit: "r/SaaS",
    status: "ready",
    userKarma: 2450,
    userCommentKarma: 1230,
    requirements: [
      { type: "min_comment_karma", label: "Minimum 10 comment karma", threshold: 10, met: true, current: 1230, progress: 100 },
    ],
    contentRules: [
      { id: "sa1", title: "No \"check out my SaaS\" posts", description: "Launch announcements without community engagement history will be removed. Build karma here first by helping others.", severity: "remove", category: "self_promotion" },
      { id: "sa2", title: "External links need context", description: "If you share a link, you must include a text summary in the post body. Link-only posts are auto-removed.", severity: "remove", category: "links" },
      { id: "sa3", title: "No asking for upvotes", description: "Asking for upvotes, engagement, or follows is a permanent ban.", severity: "ban", category: "spam" },
    ],
    restrictions: [],
    canPost: true,
    canComment: true,
  },
  {
    subreddit: "r/marketing",
    status: "limited",
    userKarma: 2450,
    userCommentKarma: 1230,
    requirements: [
      { type: "min_karma", label: "Minimum 500 karma", threshold: 500, met: true, current: 2450, progress: 100 },
      { type: "min_subreddit_karma", label: "Minimum 50 karma in r/marketing", threshold: 50, met: false, current: 12, progress: 24 },
      { type: "flair_required", label: "Post flair required", met: true },
    ],
    contentRules: [
      { id: "m1", title: "No links to your own content — ever", description: "Blog posts, YouTube videos, podcasts, newsletters — if it's yours, don't link it. Summarize the content in your post instead. Violators are permanently banned.", severity: "ban", category: "links" },
      { id: "m2", title: "No tool recommendations without disclosure", description: "If you recommend a tool you're affiliated with, you must disclose the relationship. Undisclosed affiliates are banned.", severity: "ban", category: "self_promotion" },
      { id: "m3", title: "No DM solicitation", description: "\"DM me for details\" or \"I can help, send me a message\" comments are removed and may result in a ban.", severity: "remove", category: "spam" },
      { id: "m4", title: "Flair required on all posts", description: "Posts without flair are auto-removed. Choose from: Discussion, Question, Case Study, Resource, Career.", severity: "remove", category: "formatting" },
      { id: "m5", title: "No lead magnets", description: "Don't offer free PDFs, templates, or resources that require an email signup. This is treated as spam.", severity: "ban", category: "spam" },
    ],
    restrictions: ["No direct links to your own content", "Flair required on all posts"],
    canPost: false,
    canComment: true,
  },
  {
    subreddit: "r/GrowthHacking",
    status: "limited",
    userKarma: 2450,
    userCommentKarma: 1230,
    requirements: [
      { type: "min_karma", label: "Minimum 200 karma", threshold: 200, met: true, current: 2450, progress: 100 },
      { type: "min_comment_karma", label: "Minimum 100 comment karma in sub", threshold: 100, met: false, current: 35, progress: 35 },
      { type: "min_account_age", label: "Account at least 60 days old", threshold: 60, met: true, current: 365, progress: 100 },
    ],
    contentRules: [
      { id: "g1", title: "No \"how to get followers\" spam", description: "Generic growth advice without data or case studies will be removed. Show numbers or don't post.", severity: "remove", category: "content_type" },
      { id: "g2", title: "No app/tool promotion", description: "Mentioning your own tool is only allowed if it's directly solving a problem someone asked about, and you disclose you're the maker.", severity: "remove", category: "self_promotion" },
      { id: "g3", title: "No shortened or tracked URLs", description: "bit.ly, utm-tagged links, and URL shorteners are auto-removed.", severity: "remove", category: "links" },
    ],
    restrictions: ["New accounts restricted for 7 days after joining"],
    canPost: false,
    canComment: true,
  },
  {
    subreddit: "r/sales",
    status: "locked",
    userKarma: 2450,
    userCommentKarma: 1230,
    requirements: [
      { type: "min_karma", label: "Minimum 1000 karma", threshold: 1000, met: true, current: 2450, progress: 100 },
      { type: "min_subreddit_karma", label: "Minimum 200 karma in r/sales", threshold: 200, met: false, current: 0, progress: 0 },
      { type: "approved_only", label: "Approved posters only", met: false },
    ],
    contentRules: [
      { id: "sl1", title: "No selling in the sales subreddit", description: "Ironic but strict: do not pitch your product, service, or consulting. This is for sales professionals to discuss the craft, not practice it on each other.", severity: "ban", category: "self_promotion" },
      { id: "sl2", title: "No external links without mod approval", description: "All posts with external links require moderator pre-approval. Submit via modmail first.", severity: "remove", category: "links" },
      { id: "sl3", title: "No hiring or job posts", description: "Job postings, recruiting, and \"we're hiring\" posts belong in the monthly thread only.", severity: "remove", category: "content_type" },
    ],
    restrictions: ["Must be approved by moderators to post", "Comment and build reputation first"],
    canPost: false,
    canComment: false,
  },
  {
    subreddit: "r/indiehackers",
    status: "ready",
    userKarma: 2450,
    userCommentKarma: 1230,
    requirements: [
      { type: "min_karma", label: "Minimum 10 karma", threshold: 10, met: true, current: 2450, progress: 100 },
    ],
    contentRules: [
      { id: "i1", title: "Share your link in comments, not the post", description: "Write your story/question as a text post. If people ask for the link, share it in the comments.", severity: "warn", category: "links" },
      { id: "i2", title: "No pure launch announcements", description: "\"I just launched X\" with nothing else gets removed. Share what you learned, your numbers, or ask a specific question.", severity: "remove", category: "content_type" },
    ],
    restrictions: [],
    canPost: true,
    canComment: true,
  },
  {
    subreddit: "r/smallbusiness",
    status: "limited",
    userKarma: 2450,
    userCommentKarma: 1230,
    requirements: [
      { type: "min_karma", label: "Minimum 100 karma", threshold: 100, met: true, current: 2450, progress: 100 },
      { type: "min_comment_karma", label: "Minimum 50 comment karma in sub", threshold: 50, met: false, current: 18, progress: 36 },
      { type: "custom", label: "Must participate in 3 discussions first", met: false, current: 1, threshold: 3, progress: 33 },
    ],
    contentRules: [
      { id: "sb1", title: "No self-promotion in titles", description: "Your post title cannot mention your brand, product, or service name. Frame it as a question or discussion topic.", severity: "remove", category: "self_promotion" },
      { id: "sb2", title: "No links to your own site", description: "Do not link to your website, landing page, or product. You may describe what you offer in text if asked.", severity: "remove", category: "links" },
      { id: "sb3", title: "No surveys or research requests", description: "\"Fill out my survey\" and market research posts are removed. Use r/SampleSize instead.", severity: "remove", category: "content_type" },
      { id: "sb4", title: "No unsolicited DMs to commenters", description: "DMing people who comment on your post to sell them is a permanent ban. Mods check reports.", severity: "ban", category: "behavior" },
    ],
    restrictions: ["No self-promotion in titles"],
    canPost: false,
    canComment: true,
  },
];
